### PR TITLE
Issue/9

### PR DESCRIPTION
**Pull request by Doemuu**
Implement Header, Navigation Footer and SignUp. Added different layouts

### CODE REVIEW

**Comment by Dan6erbond** [comment]
Great overall structuring of the Vue components and views, as well as assets. The layout looks good, although the design itself leaves some room for improvement. Points include:

1. Shadows: Too strong, reference material design guidelines.
2. Colors: Reference material color palettes for a more vibrant look.
3. Footer: Background stands out too much, use shadows to separate body and footer.
   * Use grey font color to stand out less.
4. Text decorations: Refrain from using underlining unless it's within a blocktext.
5. Inputs: Simplify design, make use of underlining here and remove the border radius.

**Review by Dan6erbond — CHANGES_REQUESTED** [review]
Great overall structuring of the Vue components and views, as well as assets. The layout looks good, although the design itself leaves some room for improvement. Points include:

1. Shadows: Too strong, reference material design guidelines.
2. Colors: Reference material color palettes for a more vibrant look.
3. Footer: Background stands out too much, use shadows to separate body and footer.
   * Use grey font color to stand out less.
4. Text decorations: Refrain from using underlining unless it's within a blocktext.
5. Inputs: Simplify design, make use of underlining here and remove the border radius.

**Review by Dan6erbond — CHANGES_REQUESTED** [review]
I've now made some of the changes myself; added more vibrant colors to important elements such as buttons and the header, as well as reduced the usage of colored box shadows and replaced them with material guideline elevation shadows.

The sign in layout has been updated with increased spacing, and a removal of the default Bootstrap/browser focus styling. In place the bottom border's width is increased, as well as some custom styles for the placeholder.

Further changes should be made, though - the sign in page and other input groups should make use of HTML forms to take advantage of features such as Vue's `@submit.prevent` directive as well as Bootstrap's form group/row components.

**Comment by Doemuu** [comment]
Sass opens up new possibilities in css structuring in every component. created an issue on that behalf.

**Pull request merged**
